#!/usr/bin/env bash

read -n 1 -s -r #press a key starts timer
echo "Tap any key at desired tempo, Ctrl-C to finish"
init=$(gdate +%s.%3N)
while read -n 1 -s -r
do
	((taps+=1))
	echo $taps "taps, BPM:" $(bc <<< "scale=1 ; 60*$taps/($(gdate +%s.%3N)-$init)")
done

#apparently linux can use date +%s.%3N to get milliseconds.
#macos and some other systems must use gdate from coreutils.
